# Generated by Django 3.1.7 on 2022-07-02 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
            managers=[
                ('own_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_team', models.CharField(max_length=255, verbose_name='Nombre del equipo')),
                ('flag_photo', models.ImageField(upload_to='uploads/flag', verbose_name='Foto de la bandera')),
                ('shield_photo', models.ImageField(upload_to='uploads/shield', verbose_name='Foto del escudo')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifa.country')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
            managers=[
                ('own_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_photo', models.ImageField(upload_to='uploads/shield', verbose_name='Foto del jugador')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido(s)')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('titular', models.BooleanField(default=False, verbose_name='Titular')),
                ('shirt_number', models.CharField(max_length=255, verbose_name='Numero de camiseta')),
                ('position', models.CharField(choices=[('GK', 'Arquero'), ('DF', 'Defensa'), ('MD', 'Centrocampista'), ('FW', 'Delantero')], max_length=18, verbose_name='Position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='CoachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido(s)')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('rol', models.CharField(choices=[('TC', 'Tecnico'), ('AS', 'Asistente'), ('MD', 'Medico'), ('PR', 'Preparador')], max_length=12, verbose_name='Rol')),
                ('nacionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
        ),
    ]
