# Generated by Django 3.1.7 on 2022-07-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name_country', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name_team', models.CharField(max_length=255, verbose_name='Nombre del equipo')),
                ('flag_photo', models.ImageField(upload_to='uploads/flag', verbose_name='Foto de la bandera')),
                ('shield_photo', models.ImageField(upload_to='uploads/shield', verbose_name='Foto del escudo')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.country')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('player_photo', models.ImageField(upload_to='uploads/shield', verbose_name='Foto del jugador')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido(s)')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='CoachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido(s)')),
                ('birth_date', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('TC', 'Tecnico'), ('AS', 'Asistente'), ('MD', 'Medico'), ('PR', 'Preparador')], max_length=12, verbose_name='Rol')),
                ('nacionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.team')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name_city', models.CharField(max_length=255, verbose_name='Nombre del equipo')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fifa.country')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
