# Generated by Django 3.1.7 on 2022-07-02 06:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('own_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
