# Generated by Django 3.1.7 on 2022-07-03 00:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('own_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'shirt_number'), name='Camisa por equipo'),
        ),
    ]
