# Generated by Django 3.1.7 on 2022-07-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_auto_20220702_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
