# Generated by Django 3.1.7 on 2022-07-02 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_delete_city'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('own_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fifa.country'),
        ),
    ]
