# Generated by Django 3.1.7 on 2022-07-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0004_auto_20220702_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
