# Generated by Django 3.1.7 on 2022-07-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0005_auto_20220702_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingstaff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coachingstaff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
    ]
